grafana:
  adminPassword: changeme
  service:
    type: LoadBalancer

kubelet:
  namespace: prometheus-operator

prometheus:
  prometheusSpec:
    retention: 30d

prometheusOperator:
  kubeletService:
    namespace: prometheus-operator
