apiVersion: v1
kind: Namespace
metadata:
  name: tekton-pipelines
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: tekton-pipeline
    meta.helm.sh/release-namespace: tekton-pipelines
