{{- if .Values.spark.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "jaeger.fullname" . }}-spark
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
    app.kubernetes.io/component: spark
{{- if .Values.spark.annotations }}
  annotations:
{{ toYaml .Values.spark.annotations | indent 4 }}
{{- end }}
spec:
  schedule: {{ .Values.spark.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.spark.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.spark.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "jaeger.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: spark
            {{- if .Values.spark.podLabels }}
{{ toYaml .Values.spark.podLabels | indent 12 }}
            {{- end }}
        spec:
          serviceAccountName: {{ template "jaeger.spark.serviceAccountName" . }}
          containers:
          - name: {{ include "jaeger.fullname" . }}-spark
            image: {{ .Values.spark.image }}:{{ .Values.spark.tag }}
            imagePullPolicy: {{ .Values.spark.pullPolicy }}
            env:
            {{- range $key, $value := .Values.spark.cmdlineParams }}
            - name: {{ $key | replace "." "_" | replace "-" "_" | upper | quote }}
              value: {{ $value | quote }}
            {{- end }}
            - name: STORAGE
              value: {{ .Values.storage.type }}
            {{- if eq .Values.storage.type "cassandra" }}
            - name: CASSANDRA_CONTACT_POINTS
              value: {{ template "cassandra.contact_points" . }}
            - name: CASSANDRA_KEYSPACE
              value: {{ .Values.storage.cassandra.keyspace }}
            {{- if .Values.storage.cassandra.usePassword }}
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.storage.cassandra.existingSecret }}{{ .Values.storage.cassandra.existingSecret }}{{- else }}{{ include "jaeger.fullname" . }}-cassandra{{- end }}
                  key: password
            {{- end }}
            - name: CASSANDRA_USERNAME
              value: {{ .Values.storage.cassandra.user }}
            {{- end }}
            {{- if eq .Values.storage.type "elasticsearch" }}
            - name: ES_NODES
              value: {{ template "elasticsearch.client.url" . }}
            - name: ES_NODES_WAN_ONLY
              value: {{ .Values.storage.elasticsearch.nodesWanOnly | quote }}
            {{- if .Values.storage.elasticsearch.usePassword }}
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.storage.elasticsearch.existingSecret }}{{ .Values.storage.elasticsearch.existingSecret }}{{- else }}{{ include "jaeger.fullname" . }}-elasticsearch{{- end }}
                  key: password
            {{- end }}
            - name: ES_USERNAME
              value: {{ .Values.storage.elasticsearch.user }}
            {{- end }}
            resources:
{{ toYaml .Values.spark.resources | indent 14 }}
            volumeMounts:
            {{- range .Values.spark.extraConfigmapMounts }}
              - name: {{ .name }}
                mountPath: {{ .mountPath }}
                subPath: {{ .subPath }}
                readOnly: {{ .readOnly }}
            {{- end }}
            {{- range .Values.spark.extraSecretMounts }}
              - name: {{ .name }}
                mountPath: {{ .mountPath }}
                subPath: {{ .subPath }}
                readOnly: {{ .readOnly }}
            {{- end }}
          restartPolicy: OnFailure
          volumes:
          {{- range .Values.spark.extraConfigmapMounts }}
            - name: {{ .name }}
              configMap:
                name: {{ .configMap }}
          {{- end }}
          {{- range .Values.spark.extraSecretMounts }}
            - name: {{ .name }}
              secret:
                secretName: {{ .secretName }}
          {{- end }}
        {{- with .Values.spark.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.spark.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.spark.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
{{- end -}}
