{{- if  .Values.certmanager.enabled }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-issuer
spec:
  acme:
    # The ACME production api URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ required "You must provide an email to associate with your TLS certificates. Please set certmanager.email" (default .Values.certmanager.email .Values.robomotionEmail) | quote }}
    # Enable the HTTP-01 challenge provider
    http01: {}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Release.Name }}-acme-key
{{- end }}
