{{- if not .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "external-object-store"  }}
  labels:
    app: {{ printf "%s-%s" .Release.Name "external-object-store"  }}
    chart: {{ template "robomotion.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  accesskey: {{ default "" .Values.externalObjectStore.accessKey | b64enc | quote }}
  secretkey: {{ default "" .Values.externalObjectStore.secretKey | b64enc | quote }}
{{- end }}
