{{- $host := ( index .Values.ingress.hosts 0 ) -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "robomotion-proxy.fullname" . }}
  annotations:
{{- if .Values.certmanager.enabled }}
    certmanager.k8s.io/issuer: "{{ .Release.Name }}-issuer"
{{- end }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{ toYaml .Values.proxy.ingress.annotations | indent 4 }}
spec:
{{- if $host.tls }}
  tls:
  - hosts:
    - {{ $host.name }}
    secretName: {{ $host.tlsSecret }}
{{- end }}
  rules:
  - host: {{ $host.name | quote }}
    http:
      paths:
      - path: {{ .Values.proxy.ingress.path }}
        backend:
          serviceName: {{ template "robomotion-proxy.fullname" . }}
          servicePort: 80
