apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "session-store"  }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app.kubernetes.io/name: {{ include "robomotion.name" . }}
    helm.sh/chart: {{ include "robomotion.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  secret: {{ randAlphaNum 32 }}
