apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
spec:
  selectAllByDefault: true
  replicaCount: 1
  image:
    repository: victoriametrics/vmagent
    tag: v1.87.1
  remoteWrite:
    - url: "http://vminsert-vmcluster.default.svc.cluster.local:8480/insert/0/prometheus/"