{{- if .Values.buildkit.enabled }}
{{- if .Values.multitenancy.hard }}
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: "{{ include "okteto.fullname" . }}-buildkit"
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
    to:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - "{{ .Values.multitenancy.cidr }}"
        - 169.254.169.254/32
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-registry"
          app.kubernetes.io/instance: {{ .Release.Name }}
          app.kubernetes.io/component: "registry"
          app.kubernetes.io/part-of: "okteto"
  podSelector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-buildkit"
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: "buildkit"
      app.kubernetes.io/part-of: "okteto"
  policyTypes:
  - Egress
{{- end }}
{{- end }}