apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "{{ include "okteto.fullname" . }}-daemon"
  labels:
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-daemon"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/component: "daemon"
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-daemon"
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-daemon"
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: "daemon"
        app.kubernetes.io/part-of: "okteto"
      annotations:
        app.kubernetes.io/version: "{{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      hostPID: true
      terminationGracePeriodSeconds: 0
      serviceAccountName: {{ include "okteto.fullname" . }}
      {{- if .Values.unsupported.proPlanPool }}
      tolerations:
      - key: "okteto-node-pool"
        operator: "Equal"
        value: "{{ .Values.unsupported.proPlanPool }}"
        effect: "NoSchedule"
      {{- end }}
      initContainers:
      - name: prepull 
        image: docker:stable
        command: 
          - /bin/sh
          - -c
          - "docker pull okteto/helm-installer:1.0.5 || true"
        volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
      containers:
        - name: daemon
          image: okteto/bin:1.1.18-cloud
          securityContext:
            privileged: true
          command:
            - /bin/sh
            - -c
            - "cp /usr/local/bin/* /var/okteto/bin && echo 10048576 > /proc-aux/sys/fs/inotify/max_user_watches  && sysctl -w vm.max_map_count=262144 && tail -f /dev/null"
          volumeMounts:
          - mountPath: /proc-aux
            name: proc-volume
          - mountPath: /var/okteto/bin
            name: okteto-bin
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: proc-volume
        hostPath:
          path: /proc
      - name: okteto-bin
        hostPath:
          path: /var/okteto/bin
