apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "okteto.fullname" . }}-frontend"
  labels:
    app.kubernetes.io/component: "frontend"
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-frontend"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-frontend"
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-frontend"
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: "frontend"
        app.kubernetes.io/part-of: "okteto"
    spec:
      {{- if .Values.ha }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - "{{ include "okteto.fullname" . }}-frontend"
            topologyKey: kubernetes.io/hostname        
      {{- end }}
      serviceAccountName: {{ include "okteto.fullname" . }}
      {{- if .Values.unsupported.oktetoPool }}
      tolerations:
      - key: "okteto-node-pool"
        operator: "Equal"
        value: "{{ .Values.unsupported.oktetoPool }}"
        effect: "NoSchedule"
      nodeSelector:
        okteto-node-pool: "{{ .Values.unsupported.oktetoPool }}"
      {{- end }}
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.registry }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
              protocol: TCP
          env:
          {{- if .Values.auth.google.enabled }}
            - name: GOOGLE_CLIENTID
              value: {{ .Values.auth.google.clientId }}
          {{- else if .Values.auth.github.enabled }}
            - name: GITHUB_CLIENTID
              value: {{ .Values.auth.github.clientId }}
          {{- else if .Values.auth.token.enabled }}
            - name: OKTETO_AUTH_TOKEN
              value: "true"
          {{- end }}
            - name: MIXPANEL_TOKEN
              value: {{ .Values.telemetry.token }}
          {{- if .Values.unsupported.billing.enabled }}
            - name: STRIPE_TOKEN
              value: {{ .Values.unsupported.billing.publicApiKey }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /index.html
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 3
            periodSeconds: 3    
            failureThreshold: 1
          resources:
{{ toYaml .Values.frontend.resources | indent 12 }}