apiVersion: v1
kind: Service
metadata:
  name: "{{ include "okteto.fullname" . }}-frontend"
  labels:
    app.kubernetes.io/component: "frontend"
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-frontend"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      name: frontend
  selector:
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-frontend"
    app.kubernetes.io/instance: {{ .Release.Name }}
