{{- if .Values.gc.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ include "okteto.fullname" . }}-gc"
  labels:
    app.kubernetes.io/component: "gc"
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-gc"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: "{{ .Values.gc.schedule }}"
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: "gc"
        app.kubernetes.io/part-of: "okteto"
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: "gc"
            app.kubernetes.io/part-of: "okteto"
        spec:
          serviceAccountName: {{ include "okteto.fullname" . }}
          {{- if .Values.unsupported.oktetoPool }}
          tolerations:
          - key: "okteto-node-pool"
            operator: "Equal"
            value: "{{ .Values.unsupported.oktetoPool }}"
            effect: "NoSchedule"
          nodeSelector:
            okteto-node-pool: "{{ .Values.unsupported.oktetoPool }}"
          {{- end }}
          volumes:
          - name: tls-certs
            secret:
              defaultMode: 420
              secretName: {{ .Values.wildcardCertificate.name }}
          restartPolicy: Never
          containers:
            - name: gc
              image: {{ .Values.backend.image.registry }}:{{ .Values.backend.image.tag }}
              imagePullPolicy: {{ .Values.pullPolicy }}
              args: [ "gc" ]
              envFrom:
              - configMapRef:
                  name: "{{ include "okteto.fullname" . }}"
              - secretRef:
                  name: {{ include "okteto.fullname" . }}
              volumeMounts:
                - name: tls-certs
                  mountPath: /run/secrets/tls
                  readOnly: true
{{- end }}