{{- $serviceName := include "okteto.fullname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ $serviceName }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{ if .Values.adminToken }}
    dev.okteto.com/token: "{{ .Values.adminToken }}"
    {{ else }}
    dev.okteto.com/token: "{{ randAlphaNum 32 }}"
    {{ end }}
  annotations:
    dev.okteto.com/super: "true"
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.imagePullSecrets }}
- name: {{ . }}
{{- end }}
{{- end }}

