{{- if .Values.cloud.enabled }}
{{- if .Values.wildcardCertificate.create }}
{{- $wildcard := include "okteto.wildcard" . -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
 name: {{ .Values.wildcardCertificate.name }}
 labels:
   app.kubernetes.io/part-of: "okteto"
   app.kubernetes.io/component: "wildcard"
spec:
 secretName: {{ .Values.wildcardCertificate.name }}
 issuerRef:
  {{- if .Values.cloud.provider.byo.enabled }}
   name: {{ required "A valid .Values.cloud.provider.byo.issuerName is required" .Values.cloud.provider.byo.issuerName }}
  {{- else }}
   name: {{ include "okteto.fullname" . }}
  {{- end }}
   kind: Issuer
 dnsNames:
   - "{{ $wildcard }}"
{{- end}}
{{- end}}