apiVersion: v1
kind: Service
metadata:
  name: {{ template "robomotion-auth.fullname" . }}
  labels:
    app: {{ template "robomotion-auth.fullname" . }}
    chart: {{ template "robomotion.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: {{ .Values.auth.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: http

  selector:
    app: {{ template "robomotion-auth.fullname" . }}

