{{- if not .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "external-redis"  }}
  labels:
    app: {{ printf "%s-%s" .Release.Name "external-redis"  }}
    chart: {{ template "robomotion.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  password: {{ default "" .Values.externalRedis.password | b64enc | quote }}
{{- end }}
