apiVersion: v1
kind: Service
metadata:
  name: {{ template "robomotion-scheduler.fullname" . }}-grpc
  labels:
    app: {{ template "robomotion-scheduler.fullname" . }}
    chart: {{ template "robomotion.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: {{ .Values.scheduler.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080

  selector:
    app: {{ template "robomotion-scheduler.fullname" . }}
