apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "robomotion.fullname" . }}
    chart: {{ template "robomotion.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
