---
apiVersion: v1
kind: Namespace
metadata:
  name: kapp-tekton

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapp-deployer
  namespace: kapp-tekton

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kapp-tekton-deployer-admin
subjects:
  - kind: ServiceAccount
    name: kapp-deployer
    namespace: kapp-tekton
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: tekton
  namespace: kapp-tekton
spec:
  serviceAccountName: kapp-deployer
  fetch:
    - http:
        url: https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.29.0/release.yaml
  template:
    - ytt: {}
  deploy:
    - kapp: {}
