# Please read out contributing guide to learn how to properly complete this file.
# https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md#adding-your-application

minimum_resource_requirements:
  node_count: 1
  cpu: "100m"
  memory: "128Mi"
