apiVersion: triliovault.trilio.io/v1
kind: TrilioVaultManager
metadata:
  labels:
    triliovault: triliovault
  name: triliovault-manager
spec:
  trilioVaultAppVersion: 2.6.0
  helmVersion:
    version: v3
  applicationScope: Cluster
