---
dependencies:
- name: cert-manager
  alias: certmanager
  version: 0.9.1
  repository: https://charts.jetstack.io
  condition: certmanager.enabled
- name: postgresql
  version: 8.9.4
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 10.5.7
  repository: https://charts.helm.sh/stable
  condition: redis.enabled
- name: minio
  version: 5.0.25
  repository: https://charts.helm.sh/stable
  condition: minio.enabled
- name: nginx-ingress
  version: 1.36.3
  repository: https://charts.helm.sh/stable
  condition: nginx-ingress.enabled
