---
dependencies:
- name: cert-manager
  alias: certmanager
  version: 0.9.1
  repository: https://charts.jetstack.io
  condition: certmanager.enabled
- name: postgresql
  version: 10.1.1
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 12.1.1
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: minio
  version: 4.1.0
  repository: https://charts.bitnami.com/bitnami
  condition: minio.enabled
- name: ingress-nginx
  version: 3.16.1
  repository: https://kubernetes.github.io/ingress-nginx
  condition: nginx-ingress.enabled

