apiVersion: v1
appVersion: 1.14.0
description: A Jaeger Helm chart for Kubernetes
home: https://jaegertracing.io
icon: https://camo.githubusercontent.com/afa87494e0753b4b1f5719a2f35aa5263859dffb/687474703a2f2f6a61656765722e72656164746865646f63732e696f2f656e2f6c61746573742f696d616765732f6a61656765722d766563746f722e737667
keywords:
- jaeger
- opentracing
- tracing
- instrumentation
maintainers:
- email: david.vonthenen@dell.com
  name: dvonthenen
- email: michael.lorant@fairfaxmedia.com.au
  name: mikelorant
- email: naseem@transit.app
  name: naseemkullah
- email: pavel.nikolov@fairfaxmedia.com.au
  name: pavelnikolov
name: jaeger
sources:
- https://hub.docker.com/u/jaegertracing/
version: 0.13.3
