apiVersion: v1
description: Enable Kubernetes as a backend for OpenFaaS (Functions as a Service)
home: https://www.openfaas.com
icon: https://raw.githubusercontent.com/openfaas/media/master/OpenFaaS_logo_stacked_opaque.png
keywords:
- functions
- service
maintainers:
- email: alex@openfaas.com
  name: alexellis
- email: roesler.lucas@gmail.com
  name: lucasroesler
- email: stefan.prodan@gmail.com
  name: stefanprodan
- email: rmocius@gmail.com
  name: rimusz
name: openfaas
sources:
- https://github.com/openfaas/faas
- https://github.com/openfaas/faas-netes
version: 5.2.2
