apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"gopaddle"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"gopaddle"},"subjects":[{"kind":"ServiceAccount","name":"default","namespace":"gp-lite-4-2"}]}
  name: gopaddle
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gopaddle
subjects:
- kind: ServiceAccount
  name: default
  namespace: gp-lite-4-2
