apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gopaddle
subjects:
- kind: ServiceAccount
  name: default
  namespace: gp-lite-4-2
roleRef:
  kind: ClusterRole
  name: gopaddle
  apiGroup: rbac.authorization.k8s.io
