kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ printf "%s-%s" .Release.Name "configmap"  }}
  namespace: {{ .Release.Namespace }}
data:
  clusterkey: {{ randAlphaNum 15 | quote }}
  encryptionkey: {{ randAlphaNum 15 | quote }}