###########-----STATUS PAGE------#################
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ printf "%s-%s" .Release.Name "status"  }}
    namespace: {{ .Release.Namespace }}
    labels:
        app: {{ printf "%s-%s" .Release.Name "status"  }}
spec:
    selector:
        matchLabels:
            app: {{ printf "%s-%s" .Release.Name "status"  }}
    replicas: {{ .Values.replicaCount }}
    template:
        metadata:
            labels:
                app: {{ printf "%s-%s" .Release.Name "status"  }}
        spec:
            containers:
                - image: {{ printf "%s/%s/%s:%s" .Values.image.registry .Values.image.repository "status-page" .Values.image.tag }}
                  name: {{ printf "%s-%s" .Release.Name "status"  }}
                  imagePullPolicy: {{ .Values.image.pullPolicy }}
                  env:
                    - name: FYIPE_HOST
                      value: {{ .Values.fyipe.hosts.host1.host }}
                    {{- if .Values.saas.isSaasService }}
                    - name: IS_SAAS_SERVICE
                      value: 'true'
                    {{- end }}
                    - name: NODE_ENV
                      value: 'production'
                  ports:
                      - containerPort: {{ .Values.host.statusPagePort }}
                        hostPort: {{ .Values.host.statusPagePort }}
                        name: {{ printf "%s-%s" .Release.Name "status"  }}
            restartPolicy: {{ .Values.image.restartPolicy }}
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: {{ printf "%s-%s" .Release.Name "status"  }}
    name: {{ printf "%s-%s" .Release.Name "status"  }}
    namespace: {{ .Release.Namespace }}
spec:
    ports:
        - port: {{ .Values.host.statusPageServicePort }}
          targetPort: {{ .Values.host.statusPagePort }}
    selector:
        app: {{ printf "%s-%s" .Release.Name "status"  }}
    type: {{ .Values.service.type }}
---
########################################