apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis
  labels: &RedisDeploymentLabels
    app.kubernetes.io/application: {{ .Values.applicationName }}
    app.kubernetes.io/component: op-scim-redis
spec:
  selector:
    matchLabels: *RedisDeploymentLabels
  replicas: 1
  template:
    metadata:
      labels: *RedisDeploymentLabels
    spec:
      containers:
      - name: redis
        image: {{ .Values.redisImage }}
        imagePullPolicy: Always
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-redis-svc
  labels:
    app.kubernetes.io/application: {{ .Values.applicationName }}
    app.kubernetes.io/component: op-scim-redis
spec:
  ports:
  - name: redis
    port: 6379
  selector:
    app.kubernetes.io/application: {{ .Values.applicationName }}
    app.kubernetes.io/component: op-scim-redis
  clusterIP: None