name: Auto Comment Bot
description: Auto comment issues or PRs on events triggered.

inputs:
  GITHUB_TOKEN:
    description: Your GitHub token for authentication
    required: true

  pullRequestClosed:
    required: false

runs:
  using: node12
  main: dist/index.js

branding:
  icon: send
  color: blue
