# prometheus-community/kube-prometheus-stack

grafana:
  persistence:
    enabled: true
    size: 10Gi

prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
