name: Triage
on:
  issues:
    types: [opened]
jobs:
  commentOnNewIssues:
    name: Comment On New Issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Comment On New Issues
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: comment "This for opening this issue."
